### ISSUE TITLE
Feature request: allow logs to be partitioned per party involved in query runs

### ISSUE THREAD

**Issue by akoshelev** [private-attribution/draft#44]
Currently Draft mixes logs from RC and 3 helpers, which is convenient to see overall progress. Sometimes, though, I just want to see logs from H1, H2 or RC. The current UI does not allow me to see that. This is a request to add this functionality

![Screenshot 2024-06-14 at 10 51 30 AM](https://github.com/private-attribution/draft/assets/1110516/40af0a52-e954-4591-a68b-9b610a4d0326)

**Comment by eriktaubeneck** [comment]
added w/ #63
